FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the publisher application
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/publisher ./cmd/publisher

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/bin/publisher .

CMD ["./publisher"]

